ISLANDGAME_ROSEVALE_INN_1F_ROOM1_MapScripts::
	.byte 0


ISLANDGAME_ROSEVALE_INN_1F_ROOM1_NPC::
# 5 "data/maps/ISLANDGAME_ROSEVALE_INN_1F_ROOM1/scripts.pory"
	lock
# 6 "data/maps/ISLANDGAME_ROSEVALE_INN_1F_ROOM1/scripts.pory"
	faceplayer
# 7 "data/maps/ISLANDGAME_ROSEVALE_INN_1F_ROOM1/scripts.pory"
	msgbox ISLANDGAME_ROSEVALE_INN_1F_ROOM1_NPC_Text_0
# 11 "data/maps/ISLANDGAME_ROSEVALE_INN_1F_ROOM1/scripts.pory"
	release
	return


ISLANDGAME_ROSEVALE_INN_1F_ROOM1_NPC_Text_0:
# 8 "data/maps/ISLANDGAME_ROSEVALE_INN_1F_ROOM1/scripts.pory"
	.string "This place is a complete dump. Where is\n"
	.string "the room service? The free wifi?\p"
	.string "Absolutely unacceptable. These\n"
	.string "peasants will be hearing from my lawyer!$"
