ISLANDGAME_BELLEHAVEN_HOUSE_2_MapScripts::
	.byte 0


ISLANDGAME_BELLEHAVEN_HOUSE_2_NPC::
# 5 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_2/scripts.pory"
	lock
# 6 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_2/scripts.pory"
	faceplayer
# 7 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_2/scripts.pory"
	msgbox ISLANDGAME_BELLEHAVEN_HOUSE_2_NPC_Text_0
# 12 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_2/scripts.pory"
	closemessage
# 13 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_2/scripts.pory"
	release
	return


ISLANDGAME_BELLEHAVEN_HOUSE_2_NPC_Text_0:
# 8 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_2/scripts.pory"
	.string "Ooh... have you seen my son? He hasn't\n"
	.string "come home for days...\p"
	.string "The last thing he told me before he left\n"
	.string "the house was that he was going to find\l"
	.string "a way to pay for my surgery...\p"
	.string "Oh Lugia... please bring my little boy\n"
	.string "back to me safe and sound...$"
