#ifndef GUARD_CONSTANTS_LEVEL_SCALE_H
#define GUARD_CONSTANTS_LEVEL_SCALE_H

#define TENT_MIN_LEVEL 30
#define FRONTIER_MAX_LEVEL_50   50
#define FRONTIER_MIN_LEVEL_OPEN 60
#define FRONTIER_MAX_LEVEL_OPEN MAX_LEVEL

//The first 3 respect vanilla 
//LVL_SCALE_MODE_PREFER_PLAYER: will scale opponent mons to player.
enum {
    LVL_SCALE_MODE_50,
    LVL_SCALE_MODE_OPEN,
    LVL_SCALE_MODE_BATTLE_TENT,
    LVL_SCALE_MODE_PREFER_PLAYER,
    LVL_SCALE_COUNT
};

#endif // GUARD_CONSTANTS_LEVEL_SCALE_H