#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_Islandgame1
#define MAP_FOREST_BASE_CAMP_FRONT_LAWN                   (0 | (0 << 8))
#define MAP_FOREST_BASE_CAMP_INTERIOR1F                   (1 | (0 << 8))
#define MAP_FOREST_BASE_CAMP_INTERIOR2F                   (2 | (0 << 8))
#define MAP_ISLAND_JUNGLE_ROUTE1                          (3 | (0 << 8))
#define MAP_PORY_TILE_TEST1                               (4 | (0 << 8))
#define MAP_SS_RAIN_STAIRS                                (5 | (0 << 8))
#define MAP_SS_RAIN_HALLWAY                               (6 | (0 << 8))
#define MAP_ISLANDGAME_SS_RAIN_ROOM1                      (7 | (0 << 8))
#define MAP_ISLANDGAME_SS_RAIN_ROOM2                      (8 | (0 << 8))
#define MAP_ISLANDGAME_SS_RAIN_ROOM3                      (9 | (0 << 8))
#define MAP_ISLANDGAME_SS_RAIN_CAPTAIN_ROOM               (10 | (0 << 8))
#define MAP_SS_RAIN_CAFETERIA                             (11 | (0 << 8))
#define MAP_ISLANDGAME_CAMP_PERSI                         (12 | (0 << 8))
#define MAP_ISLANDGAME_CHERIPORT                          (13 | (0 << 8))
#define MAP_ISLANDGAME_CHERIPORT_PKMNCENTER               (14 | (0 << 8))
#define MAP_ISLANDGAME_CHERIPORT_PKMNMART                 (15 | (0 << 8))
#define MAP_ISLANDGAME_CHERIPORT_LAB                      (16 | (0 << 8))
#define MAP_ISLANDGAME_CHERIPORT_HOUSE1                   (17 | (0 << 8))
#define MAP_ISLANDGAME_CHERIPORT_HOUSE2                   (18 | (0 << 8))
#define MAP_ISLANDGAME_MINTY_MEADOWS                      (19 | (0 << 8))
#define MAP_ISLANDGAME_SOUTHERN_ORANNA_PATH               (20 | (0 << 8))
#define MAP_ISLANDGAME_MINTY_MEADOWS_2                    (21 | (0 << 8))
#define MAP_ISLANDGAME_MINTY_MEADOWS_3                    (22 | (0 << 8))
#define MAP_ISLANDGAME_MINTY_MEADOWS_HOUSE                (23 | (0 << 8))
#define MAP_ISLANDGAME_TRAVELERS_TUNNEL                   (24 | (0 << 8))
#define MAP_ISLANDGAME_CENTRAL_ORANNA_PATH_1              (25 | (0 << 8))
#define MAP_ISLANDGAME_CENTRAL_ORANNA_PATH_2              (26 | (0 << 8))
#define MAP_ISLANDGAME_VERDANT_PATH                       (27 | (0 << 8))
#define MAP_ISLANDGAME_VERDANT_PATH_FISHHOUSE             (28 | (0 << 8))
#define MAP_ISLANDGAME_VERDANT_WOODS                      (29 | (0 << 8))
#define MAP_ISLANDGAME_FRESA_FARMS                        (30 | (0 << 8))
#define MAP_ISLANDGAME_NORTHERN_ORANNA_PATH               (31 | (0 << 8))
#define MAP_ISLANDGAME_ROSEVALE                           (32 | (0 << 8))
#define MAP_ISLANDGAME_AURORA_PATH                        (33 | (0 << 8))
#define MAP_ISLANDGAME_MT_AURORA_1F                       (34 | (0 << 8))
#define MAP_ISLANDGAME_MT_AURORA_2F                       (35 | (0 << 8))
#define MAP_ISLANDGAME_MAPLEGROVE                         (36 | (0 << 8))
#define MAP_ISLANDGAME_MAPLEGROVE_PKMNCENTER              (37 | (0 << 8))
#define MAP_ISLANDGAME_MAPLEGROVE_PKMNMART                (38 | (0 << 8))
#define MAP_ISLANDGAME_MAPLEGROVE_HOUSE1                  (39 | (0 << 8))
#define MAP_ISLANDGAME_MAPLEGROVE_HOUSE2                  (40 | (0 << 8))
#define MAP_ISLANDGAME_MAPLEGROVE_AUDREYS_HOUSE_1F        (41 | (0 << 8))
#define MAP_ISLANDGAME_MAPLEGROVE_AUDREYS_HOUSE_2F        (42 | (0 << 8))
#define MAP_ISLANDGAME_CAMP_PERSI_LODGE_1                 (43 | (0 << 8))
#define MAP_ISLANDGAME_CAMP_PERSI_LODGE_2                 (44 | (0 << 8))
#define MAP_ISLANDGAME_CAMP_PERSI_BERRY_HOUSE             (45 | (0 << 8))
#define MAP_ISLANDGAME_CAMP_PERSI_PKMNCENTER              (46 | (0 << 8))
#define MAP_ISLANDGAME_CAMP_PERSI_MACHETE_TREE            (47 | (0 << 8))
#define MAP_ISLANDGAME_FRESA_FARMS_DAYCARE                (48 | (0 << 8))
#define MAP_ISLANDGAME_FRESA_FARMS_HOUSE                  (49 | (0 << 8))
#define MAP_ISLANDGAME_TIDALCOVE                          (50 | (0 << 8))
#define MAP_ISLANDGAME_NORTHERN_ORANNA_PATH_FITNESS_HOUSE (51 | (0 << 8))
#define MAP_ISLANDGAME_ROSEVALE_INN                       (52 | (0 << 8))
#define MAP_ISLANDGAME_ROSEVALE_PKMNCENTER                (53 | (0 << 8))
#define MAP_ISLANDGAME_ROSEVALE_RALTS_HOUSE               (54 | (0 << 8))
#define MAP_ISLANDGAME_AURORA_WEATHER_INSTITUTE           (55 | (0 << 8))
#define MAP_ISLANDGAME_TIDALCOVE_GYM                      (56 | (0 << 8))
#define MAP_ISLANDGAME_TIDALCOVE_PKMNCENTER               (57 | (0 << 8))
#define MAP_ISLANDGAME_TIDALCOVE_PKMNMART                 (58 | (0 << 8))
#define MAP_ISLANDGAME_TIDALCOVE_BIKE_PATH_BUILDING       (59 | (0 << 8))
#define MAP_ISLANDGAME_TIDALCOVE_CYCLE_SHOP               (60 | (0 << 8))
#define MAP_ISLANDGAME_TIDALCOVE_RARE_HOUSE               (61 | (0 << 8))
#define MAP_ISLANDGAME_TIDALCOVE_GENERAL_HOUSE            (62 | (0 << 8))
#define MAP_ISLANDGAME_SOUTHERN_ORANNA_PATH_CAVE          (63 | (0 << 8))
#define MAP_ISLANDGAME_CAMP_PERSI_LODGE_1_2F              (64 | (0 << 8))
#define MAP_ISLANDGAME_CAMP_PERSI_LODGE_2_2F              (65 | (0 << 8))
#define MAP_ISLANDGAME_TRAVELERS_TUNNEL_2                 (66 | (0 << 8))
#define MAP_ISLANDGAME_ROSEVALE_HOUSE2                    (67 | (0 << 8))
#define MAP_ISLANDGAME_ROSEVALE_INN_2F                    (68 | (0 << 8))
#define MAP_ISLANDGAME_ROSEVALE_INN_2F_ROOM1              (69 | (0 << 8))
#define MAP_ISLANDGAME_ROSEVALE_INN_2F_ROOM2              (70 | (0 << 8))
#define MAP_ISLANDGAME_ROSEVALE_INN_1F_ROOM1              (71 | (0 << 8))
#define MAP_ISLANDGAME_ROSEVALE_INN_1F_ROOM2              (72 | (0 << 8))
#define MAP_ISLANDGAME_MT_AURORA_3F                       (73 | (0 << 8))
#define MAP_ISLANDGAME_MT_AURORA_2F_2                     (74 | (0 << 8))
#define MAP_ISLANDGAME_MT_AURORA_2F_3                     (75 | (0 << 8))
#define MAP_ISLANDGAME_SS_RAIN_BASEMENT                   (76 | (0 << 8))
#define MAP_ISLANDGAME_VERDANT_WOODS_SPOOKY_HOUSE         (77 | (0 << 8))
#define MAP_ISLANDGAME_VERDANT_WOODS_SPOOKY_HOUSE2        (78 | (0 << 8))
#define MAP_ISLANDGAME_CHERIPORT_LAB_2F                   (79 | (0 << 8))
#define MAP_ISLANDGAME_CHERIPORT_PKMNCENTER_2F            (80 | (0 << 8))
#define MAP_ISLANDGAME_CAMP_PERSI_PKMNCENTER_2F           (81 | (0 << 8))
#define MAP_ISLANDGAME_MAPLEGROVE_PKMNCENTER_2F           (82 | (0 << 8))
#define MAP_ISLANDGAME_TIDALCOVE_PKMNCENTER_2F            (83 | (0 << 8))
#define MAP_ISLANDGAME_ROSEVALE_PKMNCENTER_2F             (84 | (0 << 8))
#define MAP_ISLANDGAME_CENTRAL_ORANNA_PATH_GROTTO         (85 | (0 << 8))
#define MAP_ISLANDGAME_AURORA_PATH_GROTTO                 (86 | (0 << 8))

// gMapGroup_Islandgame2
#define MAP_ISLANDGAME_APPLEVINE                    (0 | (1 << 8))
#define MAP_ISLANDGAME_ROCKY_PATH                   (1 | (1 << 8))
#define MAP_ISLANDGAME_LUMINE_CAVE                  (2 | (1 << 8))
#define MAP_ISLANDGAME_BELLEHAVEN                   (3 | (1 << 8))
#define MAP_ISLANDGAME_VALLEY_OF_PEACE              (4 | (1 << 8))
#define MAP_ISLANDGAME_BELLE_CATACOMBS              (5 | (1 << 8))
#define MAP_ISLANDGAME_PLEASANT_AVENUE              (6 | (1 << 8))
#define MAP_ISLANDGAME_AETHERIA                     (7 | (1 << 8))
#define MAP_ISLANDGAME_AZURE_PATH                   (8 | (1 << 8))
#define MAP_ISLANDGAME_ARBORIA                      (9 | (1 << 8))
#define MAP_ISLANDGAME_ARBORIA_THICKET              (10 | (1 << 8))
#define MAP_ISLANDGAME_SIERRA_PATH                  (11 | (1 << 8))
#define MAP_ISLANDGAME_SIERRA_DESERT                (12 | (1 << 8))
#define MAP_ISLANDGAME_CANTALO                      (13 | (1 << 8))
#define MAP_ISLANDGAME_LUMINE_POWER_PLANT           (14 | (1 << 8))
#define MAP_ISLANDGAME_THERION_PATH                 (15 | (1 << 8))
#define MAP_ISLANDGAME_MT_THERION_1F                (16 | (1 << 8))
#define MAP_ISLADNGAME_PROMENADE_PATH               (17 | (1 << 8))
#define MAP_ISLANDGAME_APPLEVINE_NAME_RATER         (18 | (1 << 8))
#define MAP_ISLANDGAME_APPLEVINE_PKMNCENTER         (19 | (1 << 8))
#define MAP_ISLANDGAME_APPLEVINE_PKMNMART           (20 | (1 << 8))
#define MAP_ISLANDGAME_APPLEVINE_GAME_CORNER        (21 | (1 << 8))
#define MAP_ISLANDGAME_APPLEVINE_COUCH_POTATO       (22 | (1 << 8))
#define MAP_ISLANDGAME_APPLEVINE_RESTAURANT         (23 | (1 << 8))
#define MAP_ISLANDGAME_APPLEVINE_BIKE_PATH_BUILDING (24 | (1 << 8))
#define MAP_ISLANDGAME_APPLEVINE_QUEST_HOUSE        (25 | (1 << 8))
#define MAP_ISLANDGAME_ROCKY_PATH_HOUSE             (26 | (1 << 8))
#define MAP_ISLANDGAME_ROCKY_PATH_PKMNCENTER        (27 | (1 << 8))
#define MAP_ISLANDGAME_APPLEVINE_PKMNCENTER_2F      (28 | (1 << 8))
#define MAP_ISLANDGAME_AETHERIA_MUSEUM_1F           (29 | (1 << 8))
#define MAP_ISLANDGAME_AETHERIA_MUSEUM_2F           (30 | (1 << 8))
#define MAP_ISLANDGAME_AETHERIA_PKMNCENTER          (31 | (1 << 8))
#define MAP_ISLANDGAME_BELLEHAVEN_HOUSE_1           (32 | (1 << 8))
#define MAP_ISLANDGAME_BELLEHAVEN_HOUSE_2           (33 | (1 << 8))
#define MAP_ISLANDGAME_BELLEHAVEN_FOSTER_HOME       (34 | (1 << 8))

// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY      (0 | (2 << 8))
#define MAP_SLATEPORT_CITY      (1 | (2 << 8))
#define MAP_MAUVILLE_CITY       (2 | (2 << 8))
#define MAP_RUSTBORO_CITY       (3 | (2 << 8))
#define MAP_FORTREE_CITY        (4 | (2 << 8))
#define MAP_LILYCOVE_CITY       (5 | (2 << 8))
#define MAP_MOSSDEEP_CITY       (6 | (2 << 8))
#define MAP_SOOTOPOLIS_CITY     (7 | (2 << 8))
#define MAP_EVER_GRANDE_CITY    (8 | (2 << 8))
#define MAP_LITTLEROOT_TOWN     (9 | (2 << 8))
#define MAP_DEWFORD_TOWN        (10 | (2 << 8))
#define MAP_LAVARIDGE_TOWN      (11 | (2 << 8))
#define MAP_FALLARBOR_TOWN      (12 | (2 << 8))
#define MAP_VERDANTURF_TOWN     (13 | (2 << 8))
#define MAP_PACIFIDLOG_TOWN     (14 | (2 << 8))
#define MAP_ROUTE101            (15 | (2 << 8))
#define MAP_ROUTE102            (16 | (2 << 8))
#define MAP_ROUTE103            (17 | (2 << 8))
#define MAP_ROUTE104            (18 | (2 << 8))
#define MAP_ROUTE105            (19 | (2 << 8))
#define MAP_ROUTE106            (20 | (2 << 8))
#define MAP_ROUTE107            (21 | (2 << 8))
#define MAP_ROUTE108            (22 | (2 << 8))
#define MAP_ROUTE109            (23 | (2 << 8))
#define MAP_ROUTE110            (24 | (2 << 8))
#define MAP_ROUTE111            (25 | (2 << 8))
#define MAP_ROUTE112            (26 | (2 << 8))
#define MAP_ROUTE113            (27 | (2 << 8))
#define MAP_ROUTE114            (28 | (2 << 8))
#define MAP_ROUTE115            (29 | (2 << 8))
#define MAP_ROUTE116            (30 | (2 << 8))
#define MAP_ROUTE117            (31 | (2 << 8))
#define MAP_ROUTE118            (32 | (2 << 8))
#define MAP_ROUTE119            (33 | (2 << 8))
#define MAP_ROUTE120            (34 | (2 << 8))
#define MAP_ROUTE121            (35 | (2 << 8))
#define MAP_ROUTE122            (36 | (2 << 8))
#define MAP_ROUTE123            (37 | (2 << 8))
#define MAP_ROUTE124            (38 | (2 << 8))
#define MAP_ROUTE125            (39 | (2 << 8))
#define MAP_ROUTE126            (40 | (2 << 8))
#define MAP_ROUTE127            (41 | (2 << 8))
#define MAP_ROUTE128            (42 | (2 << 8))
#define MAP_ROUTE129            (43 | (2 << 8))
#define MAP_ROUTE130            (44 | (2 << 8))
#define MAP_ROUTE131            (45 | (2 << 8))
#define MAP_ROUTE132            (46 | (2 << 8))
#define MAP_ROUTE133            (47 | (2 << 8))
#define MAP_ROUTE134            (48 | (2 << 8))
#define MAP_UNDERWATER_ROUTE124 (49 | (2 << 8))
#define MAP_UNDERWATER_ROUTE126 (50 | (2 << 8))
#define MAP_UNDERWATER_ROUTE127 (51 | (2 << 8))
#define MAP_UNDERWATER_ROUTE128 (52 | (2 << 8))
#define MAP_UNDERWATER_ROUTE129 (53 | (2 << 8))
#define MAP_UNDERWATER_ROUTE105 (54 | (2 << 8))
#define MAP_UNDERWATER_ROUTE125 (55 | (2 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (3 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (3 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (3 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (3 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (3 << 8))

// gMapGroup_IndoorOldale

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (5 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (5 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (5 << 8))
#define MAP_DEWFORD_TOWN_GYM               (3 | (5 << 8))
#define MAP_DEWFORD_TOWN_HALL              (4 | (5 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (5 | (5 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (6 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (6 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (6 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (6 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (6 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (6 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (6 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (7 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (7 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (7 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (7 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (7 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (7 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (7 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (7 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (8 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (8 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (8 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (8 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (8 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (8 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (8 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (8 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (8 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (9 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (9 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (9 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (9 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (9 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (9 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (9 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (10 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (10 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (10 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (10 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (10 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (10 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (10 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (11 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (11 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (11 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (11 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (11 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (11 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (11 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (11 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (11 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (11 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (11 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (11 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (11 << 8))
#define MAP_SLATEPORT_CITY_MART                    (13 | (11 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_GYM               (0 | (12 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (12 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (12 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (12 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (12 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (12 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (12 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (12 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (13 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (13 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (13 << 8))
#define MAP_RUSTBORO_CITY_GYM               (3 | (13 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (4 | (13 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (5 | (13 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (6 | (13 << 8))
#define MAP_RUSTBORO_CITY_MART              (7 | (13 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (8 | (13 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (9 | (13 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (10 | (13 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (11 | (13 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (12 | (13 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (13 | (13 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (14 | (13 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (15 | (13 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (16 | (13 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1            (0 | (14 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (14 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (14 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (14 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (14 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (14 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (14 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (14 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (14 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (14 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (15 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (15 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (15 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (15 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (15 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (15 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (15 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (15 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (15 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (15 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (10 | (15 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (11 | (15 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (12 | (15 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (13 | (15 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (14 | (15 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (15 | (15 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (16 | (15 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (17 | (15 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (18 | (15 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (19 | (15 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (20 | (15 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (21 | (15 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (22 | (15 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_GYM               (0 | (16 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (16 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (16 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (16 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (16 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (16 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (16 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (16 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (16 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (16 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (16 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (16 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (16 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (17 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (17 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (17 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (17 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (17 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (17 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (17 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (17 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (17 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (17 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (17 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (17 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (17 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (17 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (17 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (18 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (18 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (18 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (18 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (18 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (18 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (18 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (18 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (18 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (18 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (18 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (18 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (18 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (18 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (18 << 8))

// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (19 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (19 << 8))

// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (20 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (20 << 8))

// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (21 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (21 << 8))

// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (22 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (22 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (22 << 8))

// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (23 << 8))

// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (24 << 8))

// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (25 << 8))

// gMapGroup_Dungeons
#define MAP_METEOR_FALLS_1F_1R                       (0 | (26 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (1 | (26 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (2 | (26 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (3 | (26 << 8))
#define MAP_RUSTURF_TUNNEL                           (4 | (26 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (5 | (26 << 8))
#define MAP_DESERT_RUINS                             (6 | (26 << 8))
#define MAP_GRANITE_CAVE_1F                          (7 | (26 << 8))
#define MAP_GRANITE_CAVE_B1F                         (8 | (26 << 8))
#define MAP_GRANITE_CAVE_B2F                         (9 | (26 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (10 | (26 << 8))
#define MAP_PETALBURG_WOODS                          (11 | (26 << 8))
#define MAP_MT_CHIMNEY                               (12 | (26 << 8))
#define MAP_JAGGED_PASS                              (13 | (26 << 8))
#define MAP_FIERY_PATH                               (14 | (26 << 8))
#define MAP_MT_PYRE_1F                               (15 | (26 << 8))
#define MAP_MT_PYRE_2F                               (16 | (26 << 8))
#define MAP_MT_PYRE_3F                               (17 | (26 << 8))
#define MAP_MT_PYRE_4F                               (18 | (26 << 8))
#define MAP_MT_PYRE_5F                               (19 | (26 << 8))
#define MAP_MT_PYRE_6F                               (20 | (26 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (21 | (26 << 8))
#define MAP_MT_PYRE_SUMMIT                           (22 | (26 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (23 | (26 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (24 | (26 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (25 | (26 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (26 | (26 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (27 | (26 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (28 | (26 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (29 | (26 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (30 | (26 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (31 | (26 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (32 | (26 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (33 | (26 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (34 | (26 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (35 | (26 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (36 | (26 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (37 | (26 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (38 | (26 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (39 | (26 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (40 | (26 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (41 | (26 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (42 | (26 << 8))
#define MAP_VICTORY_ROAD_1F                          (43 | (26 << 8))
#define MAP_VICTORY_ROAD_B1F                         (44 | (26 << 8))
#define MAP_VICTORY_ROAD_B2F                         (45 | (26 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (46 | (26 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (47 | (26 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (48 | (26 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (49 | (26 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (50 | (26 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (51 | (26 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                    (52 | (26 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                      (53 | (26 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (54 | (26 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (55 | (26 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (56 | (26 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (57 | (26 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (58 | (26 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (59 | (26 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (60 | (26 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (61 | (26 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (62 | (26 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (63 | (26 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (64 | (26 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (65 | (26 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (66 | (26 << 8))
#define MAP_ISLAND_CAVE                              (67 | (26 << 8))
#define MAP_ANCIENT_TOMB                             (68 | (26 << 8))
#define MAP_UNDERWATER_ROUTE134                      (69 | (26 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (70 | (26 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (71 | (26 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (72 | (26 << 8))
#define MAP_SCORCHED_SLAB                            (73 | (26 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (74 | (26 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (75 | (26 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (76 | (26 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (77 | (26 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (78 | (26 << 8))
#define MAP_SKY_PILLAR_1F                            (79 | (26 << 8))
#define MAP_SKY_PILLAR_2F                            (80 | (26 << 8))
#define MAP_SKY_PILLAR_3F                            (81 | (26 << 8))
#define MAP_SKY_PILLAR_4F                            (82 | (26 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (83 | (26 << 8))
#define MAP_SKY_PILLAR_5F                            (84 | (26 << 8))
#define MAP_SKY_PILLAR_TOP                           (85 | (26 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (86 | (26 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (87 | (26 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (88 | (26 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (89 | (26 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (90 | (26 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (91 | (26 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (92 | (26 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (93 | (26 << 8))
#define MAP_MIRAGE_TOWER_1F                          (94 | (26 << 8))
#define MAP_MIRAGE_TOWER_2F                          (95 | (26 << 8))
#define MAP_MIRAGE_TOWER_3F                          (96 | (26 << 8))
#define MAP_MIRAGE_TOWER_4F                          (97 | (26 << 8))
#define MAP_DESERT_UNDERPASS                         (98 | (26 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (99 | (26 << 8))
#define MAP_ARTISAN_CAVE_1F                          (100 | (26 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (101 | (26 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (102 | (26 << 8))
#define MAP_MARINE_CAVE_END                          (103 | (26 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (104 | (26 << 8))
#define MAP_TERRA_CAVE_END                           (105 | (26 << 8))
#define MAP_ALTERING_CAVE                            (106 | (26 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (107 | (26 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (27 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (27 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (27 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (27 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (27 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (27 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (27 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (27 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (27 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (27 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (27 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (27 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (27 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (27 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (27 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (27 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (27 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (27 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (27 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (27 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (27 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (27 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (27 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (27 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (27 << 8))
#define MAP_TRADE_CENTER             (25 | (27 << 8))
#define MAP_RECORD_CORNER            (26 | (27 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (27 << 8))
#define MAP_CONTEST_HALL             (28 | (27 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (27 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (27 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (27 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (27 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (27 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (27 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (27 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (27 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (27 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (27 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (27 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (27 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (27 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (27 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (27 << 8))
#define MAP_UNION_ROOM               (60 | (27 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (28 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (28 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (28 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (28 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (28 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (28 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (28 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (28 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (28 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (28 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (28 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (28 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (28 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (28 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (28 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (28 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (28 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (28 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (28 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (28 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (28 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (28 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (28 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (28 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (28 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (28 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (28 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (28 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (28 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (28 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (28 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (28 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (28 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (28 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (28 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (28 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (28 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (28 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (28 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (28 << 8))

// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE                          (0 | (29 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (29 << 8))

// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (30 << 8))

// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (31 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (31 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (31 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (31 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (31 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (31 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (31 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (31 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (31 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (31 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (31 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (31 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (31 << 8))

// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (32 << 8))

// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (33 << 8))

// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (34 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (34 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (34 << 8))

// gMapGroup_IndoorRoute124
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (35 << 8))

#define MAP_GROUPS_COUNT 36

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
