ISLANDGAME_ROCKY_PATH_MapScripts::
	.byte 0


ISLANDGAME_ROCKY_PATH_KarateBro::
	trainerbattle_single TRAINER_ROCKY_PATH_KARATE_BRO, ISLANDGAME_ROCKY_PATH_KarateBro_Text_0, ISLANDGAME_ROCKY_PATH_KarateBro_Text_1
	msgbox ISLANDGAME_ROCKY_PATH_KarateBro_Text_2, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_ROCKY_PATH_KarateSis::
	trainerbattle_single TRAINER_ROCKY_PATH_KARATE_SIS, ISLANDGAME_ROCKY_PATH_KarateSis_Text_0, ISLANDGAME_ROCKY_PATH_KarateSis_Text_1
	msgbox ISLANDGAME_ROCKY_PATH_KarateSis_Text_2, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_ROCKY_PATH_CyclerF::
	trainerbattle_single TRAINER_ROCKY_PATH_CYCLER_F, ISLANDGAME_ROCKY_PATH_CyclerF_Text_0, ISLANDGAME_ROCKY_PATH_CyclerF_Text_1
	msgbox ISLANDGAME_ROCKY_PATH_CyclerF_Text_2, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_ROCKY_PATH_Beauty::
	trainerbattle_single TRAINER_ROCKY_PATH_BEAUTY, ISLANDGAME_ROCKY_PATH_Beauty_Text_0, ISLANDGAME_ROCKY_PATH_Beauty_Text_1
	msgbox ISLANDGAME_ROCKY_PATH_Beauty_Text_2, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_ROCKY_PATH_Camper_F::
	trainerbattle_single TRAINER_ROCKY_PATH_CAMPER_F, ISLANDGAME_ROCKY_PATH_Camper_F_Text_0, ISLANDGAME_ROCKY_PATH_Camper_F_Text_1
	msgbox ISLANDGAME_ROCKY_PATH_Camper_F_Text_2, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_ROCKY_PATH_Gentleman::
	trainerbattle_single TRAINER_ROCKY_PATH_GENTLEMAN, ISLANDGAME_ROCKY_PATH_Gentleman_Text_0, ISLANDGAME_ROCKY_PATH_Gentleman_Text_1
	msgbox ISLANDGAME_ROCKY_PATH_Gentleman_Text_2, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_ROCKY_PATH_PsychicF::
	trainerbattle_single TRAINER_ROCKY_PATH_PSYCHIC_F, ISLANDGAME_ROCKY_PATH_PsychicF_Text_0, ISLANDGAME_ROCKY_PATH_PsychicF_Text_1
	msgbox ISLANDGAME_ROCKY_PATH_PsychicF_Text_2, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_ROCKY_PATH_PsychicM::
	trainerbattle_single TRAINER_ROCKY_PATH_PSYCHIC_M, ISLANDGAME_ROCKY_PATH_PsychicM_Text_0, ISLANDGAME_ROCKY_PATH_PsychicM_Text_1
	msgbox ISLANDGAME_ROCKY_PATH_PsychicM_Text_2, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_ROCKY_PATH_Fisherman::
	trainerbattle_single TRAINER_ROCKY_PATH_FISHERMAN, ISLANDGAME_ROCKY_PATH_Fisherman_Text_0, ISLANDGAME_ROCKY_PATH_Fisherman_Text_1
	msgbox ISLANDGAME_ROCKY_PATH_Fisherman_Text_2, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_ROCKY_PATH_KarateBro_Text_0:
	.string "My sister prefers to train more than 1\n"
	.string "Pokemon, but as for me...$"

ISLANDGAME_ROCKY_PATH_KarateBro_Text_1:
	.string "How did you defeat my Machamp!$"

ISLANDGAME_ROCKY_PATH_KarateBro_Text_2:
	.string "I will only train with my Machamp for as\n"
	.string "long as I live.$"

ISLANDGAME_ROCKY_PATH_KarateSis_Text_0:
	.string "You've met weird brother right?$"

ISLANDGAME_ROCKY_PATH_KarateSis_Text_1:
	.string "I still lost with multiple Pokemon...$"

ISLANDGAME_ROCKY_PATH_KarateSis_Text_2:
	.string "I can't deny that his Machamp is strong,\n"
	.string "but my Pokemon are stronger than his!$"

ISLANDGAME_ROCKY_PATH_CyclerF_Text_0:
	.string "How do I get back on the water path?$"

ISLANDGAME_ROCKY_PATH_CyclerF_Text_1:
	.string "Oh okay, I think I got it.$"

ISLANDGAME_ROCKY_PATH_CyclerF_Text_2:
	.string "Maybe I will here for a while, biking in\n"
	.string "grass can be fun.$"

ISLANDGAME_ROCKY_PATH_Beauty_Text_0:
	.string "Those fighters, while they are\n"
	.string "admirable, stink up the place.$"

ISLANDGAME_ROCKY_PATH_Beauty_Text_1:
	.string "You're also contributing to the stench!$"

ISLANDGAME_ROCKY_PATH_Beauty_Text_2:
	.string "I heard that there's a hidden grotto\n"
	.string "around here full of water, but I've yet\l"
	.string "to find it.$"

ISLANDGAME_ROCKY_PATH_Camper_F_Text_0:
	.string "Shh!$"

ISLANDGAME_ROCKY_PATH_Camper_F_Text_1:
	.string "Don't you see that old man walking\n"
	.string "around lost?$"

ISLANDGAME_ROCKY_PATH_Camper_F_Text_2:
	.string "I'd be careful if I were you, he looks\n"
	.string "dangerous$"

ISLANDGAME_ROCKY_PATH_Gentleman_Text_0:
	.string "Hahahahhahahahaha!$"

ISLANDGAME_ROCKY_PATH_Gentleman_Text_1:
	.string "What isn't funny?$"

ISLANDGAME_ROCKY_PATH_Gentleman_Text_2:
	.string "Most people are scared of me because I\n"
	.string "tend to be pretty laidback. Why aren't\l"
	.string "you?$"

ISLANDGAME_ROCKY_PATH_PsychicF_Text_0:
	.string "Caught you!$"

ISLANDGAME_ROCKY_PATH_PsychicF_Text_1:
	.string "Looks like I didn't have the advantage\n"
	.string "this time.$"

ISLANDGAME_ROCKY_PATH_PsychicF_Text_2:
	.string "Using my psychic powers allows me to\n"
	.string "enhance my sight, which is how I found\l"
	.string "you.$"

ISLANDGAME_ROCKY_PATH_PsychicM_Text_0:
	.string "I'm sorry, you met my sister right?$"

ISLANDGAME_ROCKY_PATH_PsychicM_Text_1:
	.string "I knew I would've lost to you as well.$"

ISLANDGAME_ROCKY_PATH_PsychicM_Text_2:
	.string "My sister is stronger than me, so we\n"
	.string "usually double battle$"

ISLANDGAME_ROCKY_PATH_Fisherman_Text_0:
	.string "I used to be a trainer in Unova.$"

ISLANDGAME_ROCKY_PATH_Fisherman_Text_1:
	.string "Darn.$"

ISLANDGAME_ROCKY_PATH_Fisherman_Text_2:
	.string "I got my own starter Pokemon in\n"
	.string "everything, but how come I wasn't able\l"
	.string "to win the championship?$"
