gText_Birch_Welcome::
	.string "Greetings, young trainer! I hope you \n"
	.string "are doing well. \p"
	.string "Congratulations on being selected to \n"
	.string "take part in our study abroad program! \p"
	.string "My name is Sheldon Palm, and I will be \n"
	.string "your professor for the duration! \p"
	.string "$"

gText_Birch_Pokemon::
	.string "The isles of Mariyama are a beautiful \n" 
	.string "paradise filled with hundreds of \n" 
	.string "different Pokémon species, and plenty \n"
	.string "more just waiting to be discovered! \p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "The isles of Mariyama are a beautiful \n" 
	.string "paradise filled with hundreds of \l" 
	.string "different Pokémon species, and plenty \l"
	.string "more just waiting to be discovered! \p"
	.string "But that's not all the isles has to \n"
	.string "offer. \p"
	.string "Our pristine waters, lush forests, and \n"
	.string "gorgeous sunsets will make for an \l" 
	.string "experience you'll never forget! \p"
	.string "Now, a little bit about me! \p"
	.string "You see, I initially traveled to \n"
	.string "Mariyama for the same reason as many \l"
	.string "others from my region: \p" 
	.string "To escape our chilling winters! \p"
	.string "But as I stuck around, I became \n"
	.string "completely enamored with the rich \l" 
	.string "culture and wildlife of the isles. \p" 
	.string "A history so profound, an ecosystem \n"
	.string "so diverse... I had to explore it all. \p"
	.string "So, I moved to the isles, eager to \n"
	.string "unravel the secrets that it hid. \p"
	.string "I've dedicated more than half my life to \n"
	.string "researching these vibrant lands. \p"
	.string "That's over twenty years! Haha, can you \n"
	.string "believe that? \p"
	.string "Unfortunately, I'm not getting any \n"
	.string "younger, so I've decided to pass my \l"
	.string "dreams and aspirations onto young \l"
	.string "and ambitious trainers like you! \p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Speaking of which, that's enough about me. I want to hear more \n"
	.string "about you!$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "I see.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "Ah, so it's {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "Well, it's a pleasure to meet you, \n"
	.string "{PLAYER}! \p"
	.string "I hope you're excited to begin your \n"
	.string "Pokémon journey here in the isles! \p"
	.string "You'll be helping me conduct field \n"
	.string "research along with another bright \l"
	.string "young trainer! \p"
	.string "But don't stress too much about the \n"
	.string "work. I want you to have fun as well!"
	.string "$"

gText_Birch_AreYouReady::
	.string "I'll be seeing you in my laboratory in a \n"
	.string "week at the port town of Cheriport. \p"
	.string "Until then, enjoy the all-expense paid \n"
	.string "cruise I've included for you! \p"
	.string "If you have a chance, try their lobster. \n"
	.string "It's amazing! \p"
	.string "I look forward to seeing you in-person, \n"
	.string "{PLAYER}. \p"
	.string "May your voyage be safe and sound."
	.string "$"
