ISLANDGAME_MT_AURORA_1F_MapScripts::
	.byte 0


ISLANDGAME_MT_AURORA_1F_SignInteract::
# 6 "data/maps/ISLANDGAME_MT_AURORA_1F/scripts.pory"
	msgbox ISLANDGAME_MT_AURORA_1F_SignInteract_Text_0, MSGBOX_SIGN
	return


ISLANDGAME_MT_AURORA_1F_SignInteract_Text_0:
# 6 "data/maps/ISLANDGAME_MT_AURORA_1F/scripts.pory"
	.string "WARNING\n"
	.string "BEWARE OF SUBZERO TEMPERATURES\p"
	.string "Attention! The caves of Mt. Aurora can\n"
	.string "get dangerously cold. Please wear\l"
	.string "proper attire before traversing.$"
