ISLANDGAME_AETHERIA_MapScripts::
	.byte 0


ISLANDGAME_AETHERIA_BattleRival::
# 4 "data/maps/ISLANDGAME_AETHERIA/scripts.pory"
	trainerbattle_single TRAINER_AETHERIA_RIVAL, ISLANDGAME_AETHERIA_BattleRival_Text_0, ISLANDGAME_AETHERIA_BattleRival_Text_1
# 11 "data/maps/ISLANDGAME_AETHERIA/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_BattleRival_Text_2, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_BattleEdea::
# 17 "data/maps/ISLANDGAME_AETHERIA/scripts.pory"
	trainerbattle_single TRAINER_AETHERIA_EDEA, ISLANDGAME_AETHERIA_BattleRival_Text_0, ISLANDGAME_AETHERIA_BattleRival_Text_1
# 24 "data/maps/ISLANDGAME_AETHERIA/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_BattleRival_Text_2, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_BattleSewer1::
# 30 "data/maps/ISLANDGAME_AETHERIA/scripts.pory"
	trainerbattle_single TRAINER_AETHERIA_SEWER_1, ISLANDGAME_AETHERIA_BattleRival_Text_0, ISLANDGAME_AETHERIA_BattleRival_Text_1
# 37 "data/maps/ISLANDGAME_AETHERIA/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_BattleRival_Text_2, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_BattleSewer2::
# 43 "data/maps/ISLANDGAME_AETHERIA/scripts.pory"
	trainerbattle_single TRAINER_AETHERIA_SEWER_2, ISLANDGAME_AETHERIA_BattleRival_Text_0, ISLANDGAME_AETHERIA_BattleRival_Text_1
# 50 "data/maps/ISLANDGAME_AETHERIA/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_BattleRival_Text_2, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_BattleSewer3::
# 56 "data/maps/ISLANDGAME_AETHERIA/scripts.pory"
	trainerbattle_single TRAINER_AETHERIA_SEWER_3, ISLANDGAME_AETHERIA_BattleRival_Text_0, ISLANDGAME_AETHERIA_BattleRival_Text_1
# 63 "data/maps/ISLANDGAME_AETHERIA/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_BattleRival_Text_2, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_BattleRival_Text_0:
# 6 "data/maps/ISLANDGAME_AETHERIA/scripts.pory"
	.string "Intro Text Here$"

ISLANDGAME_AETHERIA_BattleRival_Text_1:
# 9 "data/maps/ISLANDGAME_AETHERIA/scripts.pory"
	.string "Win Text Here$"

ISLANDGAME_AETHERIA_BattleRival_Text_2:
# 12 "data/maps/ISLANDGAME_AETHERIA/scripts.pory"
	.string "Post Text Here$"
