ISLANDGAME_BELLEHAVEN_PKMNCENTER_MapScripts::
	.byte 0


ISLANDGAME_BELLEHAVEN_PKMNCENTER_NPC_1::
# 5 "data/maps/ISLANDGAME_BELLEHAVEN_PKMNCENTER/scripts.pory"
	lock
# 6 "data/maps/ISLANDGAME_BELLEHAVEN_PKMNCENTER/scripts.pory"
	faceplayer
# 7 "data/maps/ISLANDGAME_BELLEHAVEN_PKMNCENTER/scripts.pory"
	msgbox ISLANDGAME_BELLEHAVEN_PKMNCENTER_NPC_1_Text_0
# 12 "data/maps/ISLANDGAME_BELLEHAVEN_PKMNCENTER/scripts.pory"
	release
	return


ISLANDGAME_BELLEHAVEN_PKMNCENTER_NPC_1_Text_0:
# 8 "data/maps/ISLANDGAME_BELLEHAVEN_PKMNCENTER/scripts.pory"
	.string "In the another region, I've heard a bird\n"
	.string "that looked exactly like Zapdos, except\l"
	.string "it was a fighting type instead.\p"
	.string "I wonder if you would ever get to see\n"
	.string "it?$"
