ISLANDGAME_BELLEHAVEN_PKMNCENTER_MapScripts::
	.byte 0


ISLANDGAME_BELLEHAVEN_PKMNCENTER_NPC_1::
	lock
	faceplayer
	msgbox ISLANDGAME_BELLEHAVEN_PKMNCENTER_NPC_1_Text_0
	release
	return


ISLANDGAME_BELLEHAVEN_PKMNCENTER_NPC_1_Text_0:
	.string "In the another region, I've heard a bird\n"
	.string "that looked exactly like Zapdos,\l"
	.string "except it was a fighting type instead.\p"
	.string "I wonder if you would ever get to see\n"
	.string "it?$"
