ISLANDGAME_ROSEVALE_HOUSE2_MapScripts::
	.byte 0


ISLANDGAME_ROSEVALE_HOUSE2_NPC::
	lock
	faceplayer
	msgbox ISLANDGAME_ROSEVALE_HOUSE2_NPC_Text_0
	release
	return


ISLANDGAME_ROSEVALE_HOUSE2_NPC_Text_0:
	.string "I don't get what all the craze is about\n"
	.string "these newfangled video games.\p"
	.string "My grandson spends ten hours a day\n"
	.string "doing chores on his virtual farm, while\l"
	.string "ignoring all of his real chores.\p"
	.string "Video games must have been made by the\n"
	.string "government to enslave our youth!$"
