ISLANDGAME_ROSEVALE_HOUSE2_MapScripts::
	.byte 0


ISLANDGAME_ROSEVALE_HOUSE2_NPC::
	lock
	faceplayer
	msgbox ISLANDGAME_ROSEVALE_HOUSE2_NPC_Text_0
	release
	return


ISLANDGAME_ROSEVALE_HOUSE2_NPC_Text_0:
	.string "The Silverwing Festival is Marya's most\n"
	.string "anticipated celebration.\p"
	.string "Dancing, singing, good food, Pokémon\n"
	.string "battles and performances...\p"
	.string "I'm happy to be attending my 80th\n"
	.string "festival this year!$"
