ISLANDGAME_ROSEVALE_INN_MapScripts::
	.byte 0


ISLANDGAME_ROSEVALE_INN_Interact_ArthurMom::
	msgbox ISLANDGAME_ROSEVALE_INN_Interact_ArthurMom_Text_0, MSGBOX_NPC
	return


ISLANDGAME_ROSEVALE_INN_Interact_ArthurDad::
	msgbox ISLANDGAME_ROSEVALE_INN_Interact_ArthurMom_Text_0, MSGBOX_NPC
	return


ISLANDGAME_ROSEVALE_INN_Interact_ArthurSister::
	msgbox ISLANDGAME_ROSEVALE_INN_Interact_ArthurMom_Text_0, MSGBOX_NPC
	return


ISLANDGAME_ROSEVALE_INN_Interact_Arthur::
	msgbox ISLANDGAME_ROSEVALE_INN_Interact_ArthurMom_Text_0, MSGBOX_NPC
	return


ISLANDGAME_ROSEVALE_INN_Interact_ArthurMom_Text_0:
	.string "$"
