ISLANDGAME_CAMP_PERSI_LODGE_2_2F_MapScripts::
	.byte 0


ISLANDGAME_CAMP_PERSI_LODGE_2_2F_Girl::
# 5 "data/maps/ISLANDGAME_CAMP_PERSI_LODGE_2_2F/scripts.pory"
	lock
# 6 "data/maps/ISLANDGAME_CAMP_PERSI_LODGE_2_2F/scripts.pory"
	faceplayer
# 7 "data/maps/ISLANDGAME_CAMP_PERSI_LODGE_2_2F/scripts.pory"
	msgbox ISLANDGAME_CAMP_PERSI_LODGE_2_2F_GirlTalk
# 8 "data/maps/ISLANDGAME_CAMP_PERSI_LODGE_2_2F/scripts.pory"
	release
	return


ISLANDGAME_CAMP_PERSI_LODGE_2_2F_GirlTalk::
# 11 "data/maps/ISLANDGAME_CAMP_PERSI_LODGE_2_2F/scripts.pory"
	.string "Weeeeeeeeeeeeeeeeeeeeeeeeeeee!!\p"
	.string "Sowwy, I had a lot of sugar today.$"
