ISLANDGAME_BELLEHAVEN_HOUSE_1_MapScripts::
	.byte 0


ISLANDGAME_BELLEHAVEN_HOUSE_1_NPC_1::
# 5 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_1/scripts.pory"
	lock
# 6 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_1/scripts.pory"
	faceplayer
# 7 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_1/scripts.pory"
	msgbox ISLANDGAME_BELLEHAVEN_HOUSE_1_NPC_1_Text_0
# 9 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_1/scripts.pory"
	release
	return


ISLANDGAME_BELLEHAVEN_HOUSE_1_NPC_2::
# 13 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_1/scripts.pory"
	lock
# 14 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_1/scripts.pory"
	msgbox ISLANDGAME_BELLEHAVEN_HOUSE_1_NPC_2_Text_0
# 15 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_1/scripts.pory"
	release
	return


ISLANDGAME_BELLEHAVEN_HOUSE_1_NPC_1_Text_0:
# 7 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_1/scripts.pory"
	.string "We moved here from Applevine, and we\n"
	.string "are liking it so far.\p"
	.string "It's much quieter and peaceful\n"
	.string "compared to there, except we hate\l"
	.string "moving!$"

ISLANDGAME_BELLEHAVEN_HOUSE_1_NPC_2_Text_0:
# 14 "data/maps/ISLANDGAME_BELLEHAVEN_HOUSE_1/scripts.pory"
	.string "The building is pretty old.... Looks like\n"
	.string "we need a water filter.$"
