name: Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: check labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: |
            General
            category: ability
            category: battle-ai
            category: battle-mechanic
            category: battle-tests
            category: items
            category: move animation
            category: move effect
            category: overworld
            category: pokemon
            category: sprite-issue
